//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMCONG
    {
        public int IDCC { get; set; }
        public string MSNV { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<System.TimeSpan> GIOCHAMCONG { get; set; }
        public string LOAI { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
