//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANLYNGHIPHEP
    {
        public int MANP { get; set; }
        public string MSNV { get; set; }
        public string LOAINGHI { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public Nullable<int> SONGAYNGHI { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
